
module.exports = {
    "audio": {
        "win": "assets/audio/win.ogg",
        "lose": "assets/audio/lose.ogg",
        "play": "assets/audio/play.ogg",
        "option": "assets/audio/option.ogg",
        "select": "assets/audio/select.ogg",
        "action": "assets/audio/action.ogg",
    },
    images: [
        "assets/images/horizontal/blue-blue.png",
        "assets/images/horizontal/blue-red.png",
        "assets/images/horizontal/blue-empty.png",
        "assets/images/horizontal/empty-empty.png",
        "assets/images/horizontal/red-blue.png",
        "assets/images/horizontal/red-red.png",
        "assets/images/horizontal/red-empty.png",
        "assets/images/horizontal/empty-blue.png",
        "assets/images/horizontal/empty-red.png",

        "assets/images/vertical/blue-blue.png",
        "assets/images/vertical/blue-red.png",
        "assets/images/vertical/blue-empty.png",
        "assets/images/vertical/empty-empty.png",
        "assets/images/vertical/red-blue.png",
        "assets/images/vertical/red-red.png",
        "assets/images/vertical/red-empty.png",
        "assets/images/vertical/empty-blue.png",
        "assets/images/vertical/empty-red.png",

        "assets/images/tile/blue.png",
        "assets/images/tile/blueEm.png",
        "assets/images/tile/empty.png",
        "assets/images/tile/emptyEm.png",
        "assets/images/tile/red.png",
        "assets/images/tile/redEm.png",

        "assets/images/icon/play.png",
        "assets/images/icon/difficulty/easy.png",
        "assets/images/icon/difficulty/normal.png",
        "assets/images/icon/difficulty/hard.png",
        "assets/images/icon/difficulty/impossible.png",
        "assets/images/icon/color/blue.png",
        "assets/images/icon/color/red.png",
        "assets/images/icon/sound/true.png",
        "assets/images/icon/sound/false.png",
        "assets/images/icon/tutorial.png",
    ],
};
